# Generated by Django 4.0.2 on 2022-05-04 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('field', models.CharField(blank=True, max_length=60)),
                ('farm', models.CharField(blank=True, max_length=60)),
                ('farmer', models.CharField(blank=True, max_length=60)),
                ('plot', models.CharField(blank=True, max_length=60)),
                ('rows', models.CharField(blank=True, max_length=60)),
                ('columns', models.CharField(blank=True, max_length=60)),
                ('plants', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
