# Generated by Django 4.0.2 on 2022-05-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0002_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('dailyweat', models.CharField(blank=True, max_length=60)),
                ('mintemp', models.CharField(blank=True, max_length=60)),
                ('maxtemp', models.CharField(blank=True, max_length=60)),
                ('windspeed', models.CharField(blank=True, max_length=60)),
                ('humidity', models.CharField(blank=True, max_length=60)),
                ('sunshinehrs', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
