# Generated by Django 4.0.2 on 2022-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='contact',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
