# Generated by Django 4.0.2 on 2022-05-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_tool_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='contact',
        ),
    ]
