# Generated by Django 4.0.2 on 2022-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_remove_tool_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='avgplanthei',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='croptype',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='cropvariety',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expecperi',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expecyieldpeh',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fieldcropid',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='location',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
